export const APP_CONSTANTS = {
  TITLE: "🌤️ Weather Dashboard",
  SEARCH_PLACEHOLDER: "Enter city name...",
  OUTFIT_TITLE: "👔 Outfit Suggestion",
  RECENT_SEARCHES: "🕐 Recent Searches",
  THEME_TOGGLE_ARIA: "Toggle theme",
  ERROR_PREFIX: "⚠️",
  SEARCH_ICON: "🔍",
  LOADING_ICON: "🔄",
  SUN_ICON: "☀️",
  MOON_ICON: "🌙",
  WIND_LABEL: "💨 Wind Speed",
  HUMIDITY_LABEL: "💧 Humidity",
  WIND_UNIT: "km/h",
  HUMIDITY_UNIT: "%",
  TEMPERATURE_UNIT: "°C",
};

export const POPULAR_CITIES = [
  "New York",
  "London",
  "Paris",
  "Tokyo",
  "Sydney",
  "Los Angeles",
  "Chicago",
  "Miami",
  "Berlin",
  "Amsterdam",
  "Barcelona",
  "Rome",
  "Moscow",
  "Dubai",
  "Singapore",
  "Hong Kong",
  "Toronto",
  "Vancouver",
  "Montreal",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Bangkok",
  "Seoul",
  "Beijing",
  "Shanghai",
  "Madrid",
  "Lisbon",
  "Vienna",
  "Zurich",
  "Stockholm",
  "Oslo",
  "Copenhagen",
  "Helsinki",
  "Prague",
  "Budapest",
  "Warsaw",
  "Athens",
  "Istanbul",
  "Cairo",
  "Lagos",
  "Nairobi",
  "Johannesburg",
  "Cape Town",
  "Casablanca",
  "Tunis",
  "Algiers",
  "Rabat",
  "Riyadh",
  "Doha",
  "Kuwait City",
  "Manama",
  "Abu Dhabi",
  "Muscat",
  "Tehran",
  "Baghdad",
  "Damascus",
  "Amman",
  "Beirut",
  "Tel Aviv",
  "Jerusalem",
  "Karachi",
  "Lahore",
  "Islamabad",
  "Dhaka",
  "Colombo",
  "Kathmandu",
  "Kuala Lumpur",
  "Jakarta",
  "Manila",
  "Ho Chi Minh City",
  "Hanoi",
  "Phnom Penh",
  "Yangon",
  "Vientiane",
  "Bandar Seri Begawan"
];
